//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsedMaterial
    {
        public int Id { get; set; }
        public int Material { get; set; }
        public int TechnicsUnit { get; set; }
        public System.DateTime DateOfUse { get; set; }
        public int QuantityOfMaterial { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Technics Technics { get; set; }
    }
}
